config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :articles
  resources :news_pages

  get 'pages/articles'

  get 'pages/videos'

  get 'pages/new'
  

  devise_for :users
  
  resources :topics do 
    resources :posts, only: [:create, :update, :destroy]
  end
  
  resources :users
  
  root 'posts#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :posts
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_user.topics.build(topic_params)
    # @topic.user_id = current_user.id
    

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :user_id, :post_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic, :html => {class: "form-horizontal"}) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topics.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="forum-group">
     <%= f.label :name, class: "control-label col-md-1" %>
   <div class="col-md-8"> 
    <%= f.text_field :name, class: "form-control" %>
   </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 ">
        <%= f.submit class: "btn btn-primary btn-md" %>
    </div>
  </div>
</div>
<% end %>

app/views/topics/edit.html.erb
<h1>Update Your Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1 align="center">Listing Topics</h1><br><br>

    <% @topics.each do |topic| %>
    <div class="row">
    <div class="col-md-12">
    <div class="panel panel-default" align="center">
    <table class="table">
      <tr>
        <th id="user-info" style="width: 20%"><%= image_tag topic.user.photo.url(:small), class: "img-circle" %><%= link_to topic.user.first_name, users_path(@user) %></th>
        <th>
          <h3 style="margin-left: 40px; text-align: justify"><%= link_to topic.name, topic_path(topic), style: "padding: 0px" %></h3>
        </th>
        <th style="width: 10%; text-align: center">Comments
          <p> <%= link_to topic.posts.count, topic_posts_path(topic) %></p>
        </th>
        <% if current_user %>
        <th>
          <div class="dropdown">
             <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Options
              <span class="caret"></span>
             </button>
              <ul class="dropdown-menu"> 
              <li><%= link_to 'Show', topic %></li>
              <li><%= link_to 'Edit', edit_topic_path(topic) %></li>
              <li><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </th>
        <% end %>
        </tr>
    </table>
    </div>
  </div>
  </div>

    <% end %>
    
<br>

<%= link_to 'New Topic', new_topic_path, class: "btn btn-success btn-md" %>

app/views/topics/new.html.erb
<h2 align="center">Create New Topic</h2><br><br>

<%= render 'form' %><br><br>
<div class="container">
  <%= link_to 'Back Listings', topics_path, class: "btn btn-xs btn-warning" %>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="topic-header">
<table>
  <tr>
    <th style="width: 93%;"><h1 align="center"><%= link_to @topic.name, topics_path %></h1></th>
    <th width="5%">
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">More
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <% if current_user %>
          <li><%= link_to 'Edit', edit_topic_path(@topic)%></li>
          <li><%= link_to 'Back', topics_path %></li>
          <% end %>
          <% if current_user.try(:admin?) %>
          <li><%=  link_to "Delete", topic_path(@topic), method: :delete, data: {confirm: "Are you sure you want to delete it?"} %></li>
          <% end %>
        </ul>
      </div>
  </th>
  </tr>
</table>
</div>
<p>
  <strong>Created by:</strong>
  <%= link_to @topic.user.email, user_path(@topic) %>
  <b> Created at:</b>
  <%= time_ago_in_words(@topic.created_at) %> ago
   
</p>

   

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Posts<span class="badge" style="margin-left: 2px; background-color: #f06292;"><%= @topic.posts.size %></span></h2>
      <%=  render @topic.posts %>
    </div>
  </div>
  
  <h2> Add Posts:</h2>
  <%= render "posts/form" %>
<div>