config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :articles
  resources :news_pages

  get 'pages/articles'

  get 'pages/videos'

  get 'pages/new'
  

  devise_for :users
  
  resources :topics do 
    resources :posts, only: [:create, :update, :destroy]
  end
  
  resources :users
  
  root 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :topics
  has_many :posts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :date_of_birth, presence: true
  validates :gender, presence: true

  has_attached_file :photo, styles: {large: "600x600", medium: "300x300", thumb: "100x100", small: "50x50#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  
  
  def index
    @users = User.all
    @currentUser = current_user.id
  end

  
  def show
  end

  
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :date_of_birth, :email, :gender, :photo, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: { multipart: :true, class: 'form-horizontal' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
  <div class="form-group">
    <%= f.label :first_name, class: 'col-sm-3 control-label'  %>
    <div class="col-sm-6">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-user"></i>
        </span>
        <%= f.text_field :first_name, autofocus: true, class: 'form-control', placeholder: "First Name"   %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, class: 'col-sm-3 control-label'  %>
    <div class="col-sm-6">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-user"></i>
        </span>
        <%= f.text_field :last_name, autofocus: true, class: 'form-control', placeholder: "Last Name"  %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'col-sm-3 control-label'  %>
    <div class="col-sm-6">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-envelope"></i>
        </span>
        <%= f.email_field :email, class: 'form-control', placeholder: "Email Address"   %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-lock"></i>
        </span>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Type minimum-8 characters'  %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="glyphicon glyphicon-lock"></i>
        </span>
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: "Retype your password" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth, class: 'col-sm-3 control-label'  %>
    <div class="col-sm-6">
      <%= f.date_select :date_of_birth, start_year: 1950, end_year: 2000, class: 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
        <%= f.label :photo, class: 'col-sm-3 control-label'  %>
        <div class="col-sm-6">
            <%= f.file_field :photo %>
        </div>
    </div>

   <div class="form-group">
        <%= f.label :gender, "Gender", class: 'col-sm-3 control-label'  %>
        <div class="col-sm-6">
            <%= f.radio_button :gender, "female"  %> <%= f.label :gender, "Female" %>
            <%= f.radio_button :gender, "male" %> <%= f.label :gender, "Male" %>
        </div>
    </div>

    <div class="form-group">
      <%= f.label :bio, class: 'col-sm-3 control-label'%>
        <div class="col col-sm-6">
          <div class="input-group">
            <span class="input-group-addon">
              <i class="glyphicon glyphicon-pencil"></i>
            </span>
            <%= f.text_area :bio, placeholder: "Write brief information about yourself...", class: "form-control" %>
          </div>
        </div>
    </div>

  <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <%= f.submit "Sign Up", class: "btn btn-primary" %>
        </div>
    </div>
  <% end %>
</div>

app/views/users/_posts.html.erb
<% obj.each do |post| %>
<div class="row">
  <div class="well wel-lg">
    <h4 align="center" id="title"><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.text %></p>
    <div class="article-meta-details">
        <small>Created by: <%= link_to post.user.try(:first_name)%>,
        <%= time_ago_in_words(post.created_at) %> ago,

      last updated: <%= time_ago_in_words(post.updated_at) %> ago</small>
    </div>
      <% if current_user %>
        <div>
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
          <%=  link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are 
            you sure you want to delete it?"}, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
  </div>
</div>
<% end %>


<%= link_to 'New Post', new_post_path, class: "btn btn-lg btn-success" %><br>

app/views/users/edit.html.erb
<h1 align="center">Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1 align="center">All GO-IELTS site Users</h1>
<div align="center">
  <ul class="listing">
    <% @users = User.all %>
    <% @users.each do |user| %>
    <div class="row">
      <div class="well col-md-6 col-md-offset-3">
        <li><%= link_to image_tag(user.photo.url(:small), class: 'img-circle'), user_path(user), class: 'img-circle'%></li>
        <li><strong><%= link_to user.email, user_path(user), style: "align: center" %></strong></li>
        <li>Total posts: <b><%= user.posts.count%></b></li>
      </div>
    </div>
    <% end %>
  </ul>
</div>

   
  

app/views/users/show.html.erb
<h2 align="center">Welcome <%= @user.first_name %>!</h2>
  <div class="row"><br>
  <div class="col col-md-4">
    <div class="well">
      <%= image_tag @user.photo.url(:medium), class: 'img-circle'%><br><br>
      <p align="center">Number of my posts: <%= link_to @user.posts.count, topic_posts_path(@user)  %></p>
    </div>
  </div>
  <div class="col col-md-6">
  <div class="well well-">
   <table class="table table-striped">
     <tr>
       <th>First name</th>
       <td><%= @user.first_name %></td>
     </tr>
     <tr>
       <th>Last name</th>
       <td><%= @user.last_name %></td>
     </tr>
     <tr>
       <th>Birthday</th>
       <td><%= @user.date_of_birth.strftime("%m/%d/%Y") %></td>
     </tr>
     <tr>
       <th>Email</th>
       <td><%= @user.email %></td>
     </tr>
     <tr>
       <th>Gender</th>
       <td><%= @user.gender %></td>
     </tr>
     <tr>
       <th>Brief Information</th>
       <td><%= @user.try(:bio) %></td>
     </tr>
   </table>
</div>
</div>
</div>