config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :articles
  resources :news_pages

  get 'pages/articles'

  get 'pages/videos'

  get 'pages/new'
  

  devise_for :users
  
  resources :topics do 
    resources :posts, only: [:create, :update, :destroy]
  end
  
  resources :users
  
  root 'posts#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer" id="footer">
  <div class="container">
      <nav align="center">
      <ul>
      <small> Copyright &copy; by <a href="">Alisher Musurmonov,</a></small>
        <li><%= link_to "About" %></li>
        <li><%= link_to "Help" %></li>
        <li><%= link_to "Contact" %></li>
      </ul>
    </nav>  
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="body-wrapper">
  
  <div id="user-menu">
    <% if current_user%>

      <ul class="nav navbar-nav navbar-right">
        <li><a rel="nofollow" data-method="delete" href="/users/sign_out" ><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="glyphicon glyphicon-user">Your Profile<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
          </ul>
        </li>
      </ul>

      <% else %>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
    <% end %>
  </div>
  <%= image_tag ("page1"), id: "nav-img" %>
  
  <div id="nav-bar">
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Go-IELTS", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "News", news_pages_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Videos Casts", videos_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resorces<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="listening">Listening</a></li>
            <li><a href="reading">Reading</a></li>
            <li><a href="speaking">Speaking</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="writing">Writing</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="downloads">Downloads</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", topics_path %></a></li>
        <% if current_user %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="glyphicon glyphicon-user">Users<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All User", users_path %></li>
          </ul>          
          </ul>
        </li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </div>

</div>

app/views/layouts/_sign_up.html.erb
<div id="body-wrapper">
  <div id="nav-bar">
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Go-IELTS", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "News", news_pages_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Videos Casts", videos_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resorces<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="listening">Listening</a></li>
            <li><a href="reading">Reading</a></li>
            <li><a href="speaking">Speaking</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="writing">Writing</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="downloads">Downloads</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", topics_path %></a></li>
        <% if current_user %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="glyphicon glyphicon-user">Users<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All User", users_path %></li>
          </ul>          
          </ul>
        </li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'shared/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>